name: cursor-theme-bibata
build-base: core24
base: bare
version: '2.0.7'
platforms:
  all:
    build-on: [amd64]
    build-for: [all]
summary: Bibata cursors
description: |
  A Snap that allows you to use Bibata cursors in Snap apps
grade: stable
confinement: strict

slots:
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/share/icons/Bibata-Modern-Amber
        - $SNAP/share/icons/Bibata-Modern-Amber-Right
        - $SNAP/share/icons/Bibata-Modern-Classic
        - $SNAP/share/icons/Bibata-Modern-Classic-Right
        - $SNAP/share/icons/Bibata-Modern-Ice
        - $SNAP/share/icons/Bibata-Modern-Ice-Right
        - $SNAP/share/icons/Bibata-Original-Amber
        - $SNAP/share/icons/Bibata-Original-Amber-Right
        - $SNAP/share/icons/Bibata-Original-Classic
        - $SNAP/share/icons/Bibata-Original-Classic-Right
        - $SNAP/share/icons/Bibata-Original-Ice
        - $SNAP/share/icons/Bibata-Original-Ice-Right
parts:
  bibata-cursors:
    plugin: dump
    source: https://github.com/Kyuyrii/cursor-theme-bibata-snap/releases/download/cursor-theme-bibata/bibata-cursors-v2.0.7.zip
    organize:
      icon-themes: share/icons
    prime:
      - share/icons/
